### ISSUE TITLE
polyfill can't read data: `TypeError: response.buffer is not a function`

### ISSUE THREAD

**Issue by gnunicorn** [joshuef/safe-js#13]
Trying to read structured data with the polyfill for local development, I run into a problem that the safe-js internals are failing to read the response properly with `TypeError: response.buffer is not a function(…)`

Investigating this further, it turns out safe-js is using the `response.buffer`-feature, which is [node only](https://www.npmjs.com/package/node-fetch) and not part of the whatwg standard ([mdn](https://developer.mozilla.org/en-US/docs/Web/API/Response), [living spec](https://fetch.spec.whatwg.org/#response-class)). Though the lib claims to use isomorphic-fetch (which it depends on npm-wise), it is actually relying on node-fetch. Thus it works within the browser, but not with the polyfill.

Not sure if we can just use `response.blob()` for these cases or want to switch to a `response.buffer ? response.buffer() : response.blob()`.

**Comment by joshuef** [comment]
Hey @gnunicorn do you know what's failing exactly internally reading response buffer?

[`getFile`](https://github.com/joshuef/safe-js/blob/master/src/nfs.js#L135-L150) should just be returning the response for use, which going off of [MDN methods](https://developer.mozilla.org/en-US/docs/Web/API/Response#Methods) should still provide the blob/array buffer methods for access.

I assume safejs is failing somewhere in the fetch itself here, then?

**Comment by gnunicorn** [comment]
> getFile should just be returning the response for use, which going off of MDN methods should still provide the blob/array buffer methods for access.

There is no `buffer()`-method on MDN.... 

The browser provides `arrayBuffer` and `blob`, but we are calling `buffer`.

**Comment by joshuef** [comment]
Ah, sorry I totally missed the structured data part above.

My first thought would be that we move to something similar as with `nfs.getFile` where we leave it up to the user as to how they parse the response? (Leaving the door open to read partial data and utilise streams etc.) 

I've not yet got into the new APIs in any serious way, though.  So I'm not sure if for structuredData we'd want to be choosing/helping/forcing a parsed response on the user? (I understand file contents will likely be much larger/varied). So if this makes sense for structuredData then your suggestion seems good to me 👍 , otherwise I'd opt for simply returning the response to be handled as the user/app sees fit.
